version: '3'
services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - mtstest_db:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=mtstest_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/pgsql/data

volumes:
  mtstest_db: