version: '3'
services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - mtstest_db:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=mtstest_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/pgsql/data


  logstash:
    image: logstash
    restart: on-failure
    ports:
      - 25681:25681
    volumes:
      - logs:/log
    links:
      - elasticsearch
    build:
      context: ./
      dockerfile: Dockerfile-logstash

  elasticsearch:
    image: elasticsearch:5
    restart: on-failure
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  kibana:
    image: kibana:5.5.2
    restart: on-failure
    ports:
      - 5601:5601
    links:
      - elasticsearch

volumes:
  mtstest_db:
  logs:


